### ISSUE TITLE
Getting error after installing updated plugin imagemagick

### ISSUE THREAD

**Issue by SimoIT** [NodeBB/nodebb-plugin-imagemagick#10]
Hi there,
I recently installed a new version of imagemagick plugin (2.0.6) but still got some issues as the previous version was showing up:

![Error_IM_206](https://github.com/NodeBB/nodebb-plugin-imagemagick/assets/145457301/149522c3-a936-4679-a326-02ee4a6dcef3)

Do you know how to fix it?

Thanks and Best
Simone

**Comment by julianlam** [comment]
Seems to suggest that it is not able to call the underlying imagemagick binary. Make sure that it is installed properly on the server.
