### ISSUE TITLE
Error on uploading gif

### ISSUE THREAD

**Issue by Flopet** [NodeBB/nodebb-plugin-imagemagick#5]
![screenshot from 2016-09-14 14 07 47](https://cloud.githubusercontent.com/assets/7575572/18524030/c49b4b04-7a84-11e6-9dc3-4eef3586b0cd.png)

![screenshot from 2016-09-14 14 10 00](https://cloud.githubusercontent.com/assets/7575572/18524083/f7af5008-7a84-11e6-86f2-82e20b744c0b.png)

**Comment by julianlam** [comment]
The imagemagick program itself must be installed on your server.
