### ISSUE TITLE
No gifs for avatars

### ISSUE THREAD

**Issue by ghost** [NodeBB/nodebb-plugin-imagemagick#7]
Can we get these? i'm guessing it's due to NodeBB disallowing .gif in the file chooser.
Also, ".gif" doesn't show up in the list of accepted file types when uploading a cover image, although they are accepted.

Might be more of an issue from NodeBB than this plugin.

**Comment by barisusakli** [comment]
Is this still happening on nodebb 1.5.1?

**Comment by Crushedice** [comment]
yes. and still now on 1.8,2 ... im trying everything already

**Comment by HeraKumi** [comment]
Still happening on 1.10.1 
Shows up as activated on the plugins tab

Also doesn’t show ‘gif’ when try to upload a poor file picture 🤔

This might be a dead repo

**Comment by barisusakli** [comment]
I believe since the addition of the cropper in nodebb gifs don't work.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/issues/7920
