### ISSUE TITLE
Couldn't find convert. Did you install imagemagick?

### ISSUE THREAD

**Issue by loid345** [NodeBB/nodebb-plugin-imagemagick#9]
nodebb v. 1.19.1
nodebb-plugin-imagemagick v. 2.1.1
imagemagick v. 8:6.9.10.23+dfsg-2.1ubuntu11.4
nodebb log 2022-01-24T09:42:51.866Z [4567/10407] - warn: Couldn't find convert. Did you install imagemagick?

**Comment by julianlam** [comment]
You have to install the imagemagick binary on your system. That's what the error message is saying.
